# Generated by Django 3.1 on 2020-08-16 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200815_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='game_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='game.game'),
        ),
    ]
