# Generated by Django 3.1 on 2020-08-16 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.game'),
        ),
    ]
